# Taskfile.yml

version: '3'

tasks:
  env-install:
    desc: Install the environment
    cmds:
      - pip install -r requirements.txt
      - cd transform && dbt deps
      - pre-commit install

  dbt-docs:
    desc: Run dbt docs generate
    cmds:
      - cd transform && dbt docs generate
      - cd transform && dbt docs serve

  format-code:
    desc: Code formating
    cmds:
      - sqlfmt ./transform/models
      - sqlfmt ./transform/tests
  duckdb:
    desc: Run duckdb-ide
    cmds:
      - harlequin "/workspaces/skuld_getting_started/data/db_dev.duckdb" 

  run-ibnr:
    - load_data.py
    - dbt build -s ibnr_mart
    - export_azure.py
